version: '3.9'

services:
    postgresql:
        image: postgres:${DOCKER_IMAGE_VERSION_POSTGRESQL}
        container_name: ${CONTAINER_NAME_PREFIX}-PostgreSQL
        hostname: ${CONTAINER_HOST_PREFIX}-postgresql
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - TZ=${POSTGRESQL_TIMEZONE}
            - PGTZ=${POSTGRESQL_TIMEZONE}
        volumes:
            - ${VOLUME_POSTGRESQL}:/var/lib/postgresql/data
        networks:
            default:
                ipv4_address: ${IPV4_POSTGRESQL}
        ports:
            - '${PORT_POSTGRESQL}:5432'
        restart: unless-stopped

networks:
    default:
        driver: bridge
        name: ${NETWORK_NAME}
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
    share:
        name: ${SHARING_NETWORK_NAME}
